### ISSUE TITLE
Scrapping Tool change

### ISSUE THREAD

**Issue by copy-ninja1** [ukor/demo-scraapper-puppeteer#3]
The use of puppeteer for the scrapping is a good idea but I think puppeteer is too expensive for use. 
I propose using cheerio.js it's lighter than puppeteer

**Comment by ukor** [comment]
The scrapping tool use is dependent on the project need. Puppeteer was picked for a reason.  I need all the JavaScript and  to be fully loaded. 

This is just a demo project. The full requirements for the project requires page interaction and JavaScript to be executed.
